name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: musl-gcc Install
      run: apt-get install musl-tools
    
    - name: Target Install
      run: rustup target install x86_64-unknown-linux-musl
    
    - name: Build
      run: cargo build --target=x86_64-unknown-linux-musl --verbose
      
    - name: Run tests
      run: cargo test --verbose
